### ISSUE TITLE
Evaluate lychee as a broken link checker

### ISSUE THREAD

**Issue by dreadwarrior** [dreadwarrior/dreadwarrior.github.io#101]
Integrate broken link check for:

- cover images (coverUri)
- source URLs (source)
- catalogue permalinks (cataloguePermalink)

CLI: https://github.com/lycheeverse/lychee
GitHub Actions: https://github.com/lycheeverse/lychee-action

**Comment by dreadwarrior** [comment]
Workflow snippet for creating issues from report files:

```
      - name: Link Checker - Book source URLs
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --config ./lychee-ci.toml --format markdown

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee-report.md
          labels: report, automated issue, bug
```
